# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
#my config
version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  node: circleci/node@5.1.0
  
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: vupqh/mycv-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - checkout
      
      - run: 
          name: stop and remove existing container
          command: docker-compose stop
      - run: 
          name: remove existing container
          command: docker-compose rm -f
      - run: 
          name: pull latest image
          command: docker-compose pull
      - run: 
          name: start container
          command: docker-compose up -d

workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build-and-push
